version: "3"

services:
  db:
    container_name: db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: divorces
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 10s
        timeout: 5s
        retries: 1

  app:
    container_name: app
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db :
          condition: service_healthy
    environment:
      DB_SERVER: db:5432
      DB_USER: postgres
      DB_PASSWORD: pass123

volumes:
  db: