---
loadbalancer:
  hosts:
    lb01:
      ansible_host: lb01
webserver:
  hosts:
    app01:
      ansible_host: app01
    app02:
      ansible_host: app02
database:
  hosts:
    db:
      ansible_host: db
      ansible_python_interpreter: /usr/bin/python3
control:
  hosts:
    control:
      ansible_host: control