apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL2doY3IuaW8iOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoiRWxpdGVPbmVUdWJlIiwKICAgICAgICAgICAgInBhc3N3b3JkIjoiZ2hwX05Jd3ZWUTUxdEpWMTVadnY2b3Z3eGN2eThFNGd5aDEyVzFtOSIsCiAgICAgICAgICAgICJlbWFpbCI6ImVsaXRlb25ldHViZUBnbWFpbC5jb20iLAogICAgICAgICAgICAiYXV0aCI6IlJXeHBkR1ZQYm1WVWRXSmxPbWRvY0Y5T1NYZDJWbEUxTVhSS1ZqRTFXbloyTm05MmQzaGpkbms0UlRSbmVXZ3hNbGN4YlRrPSIKICAgIAl9CiAgICB9Cn0=