apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: divorce-pvc
  namespace: default
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: 400Mi
    storageClassName: divorce-sc