apiVersion: v1
kind: Service
metadata:
  name: divorce-service
  namespace: default
spec:
    selector:
        app: divorce
    ports:
      - protocol: TCP
        port: 8080
        name: divorce-service
        targetPort: 8080
    type: ClusterIP