---
- hosts: database
  become: yes

  vars_files:
    - ./vars/db.yml

  pre_tasks:
    - name: "Install packages with apt"
      apt: "name={{ item }}  state=present update_cache=yes"
      with_items:
        - postgresql
        - python3-psycopg2

  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql

    - name: "Create app database"
      postgresql_db:
        state: present
        name: "{{ db_name }}"
      become_user: postgres

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: yes
      become_user: postgres

    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres

    - name: Enable TCP/IP connections
      lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        regexp: '^#listen_addresses'
        line: "listen_addresses = '*'"
        state: present
      become: yes
      become_user: postgres
      notify:
        - restart postgresql

    - name: Allow all connections
      lineinfile:
        path: /etc/postgresql/12/main/pg_hba.conf
        regexp: '^host'
        line: "host all all 0.0.0.0/0 trust"
      notify:
        - restart postgresql

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted