---
- hosts: k8s
  become: true
  become_user: root

  tasks:
    - name: Apply kubectl yml files
      command: kubectl apply -f {{ item }}
      with_fileglob:
        - k8s/divorce/*.yml
      args:
        chdir: ~/workspace/k8s/
        executable: /bin/bash