---
- hosts: webserver
  become: yes

  tasks:
    - name: Install openjdk-17-jdk
      apt: name=openjdk-17-jdk state=latest update_cache=yes force_apt_get=yes

    - name: Install Maven 3.9.2
      command: curl -O https://dlcdn.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.zip
      args:
          chdir: /home/ubuntu

    - name: Install Unzip
      apt: name=unzip state=latest update_cache=yes force_apt_get=yes

    - name: Unzip Maven
      unarchive: src=/home/ubuntu/apache-maven-3.9.2-bin.zip dest=/home/ubuntu remote_src=yes

    - name: Install Git
      apt: name=git state=latest update_cache=yes force_apt_get=yes

    - name: Clone Spring Boot Application
      git: repo=https://github.com/EliteOneTube/divorce_app.git
              dest=/home/ubuntu/spring-boot
              version=HEAD

    - name: Build Spring Boot Application
      shell: mvn clean install -DskipTests
      args:
          chdir: /home/ubuntu/spring-boot
          executable: /bin/bash
      environment:
          PATH: /home/ubuntu/apache-maven-3.9.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

    # - name: Stop any running Spring Boot Application
    #   shell: fuser -n tcp -k 8080
    #   args:
    #       executable: /bin/bash

    - name: Run Spring Boot Application
      shell: nohup mvn exec:java -Dexec.mainClass=gr.dit.hua.divorce.DivorceApplication &
      args:
          chdir: /home/ubuntu/spring-boot
          executable: /bin/bash
      environment:
          PATH: /home/ubuntu/apache-maven-3.9.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
          DB_SERVER: "{{ hostvars['db'].ansible_host }}"
          DB_USER: "postgres"
          DB_PASSWORD: "pass123"